services:
  # worker:
  #   build:
  #     context: .
  #     dockerfile: worker.dockerfile
  #   volumes: ["./app:/app/app"]
  #   env_file: .env
  #   depends_on: [redis]

  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --requirepass
      - admin
      - --user
      - admin
      - on
      - ">admin"
      - "~*"
      - "&*"
      - +@all
    ports: ["6379:6379"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:admin
    ports: ["8081:8081"]
    depends_on: [redis]
